# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: cypress/base:8
      
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v2a-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v2a-dependencies-
      - restore_cache:
          keys:
            - v2b-dependencies-{{ checksum "demo/package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v2b-dependencies-
      - restore_cache:
          keys:
            - v2c-dependencies-{{ checksum "packages/jarl-react/package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v2c-dependencies-
      - restore_cache:
          keys:
            - v2d-dependencies-{{ checksum "packages/jarl-react-native/package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v2d-dependencies-
      - restore_cache:
          keys:
            - v2e-dependencies-{{ checksum "packages/jarl-react-redux/package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v2e-dependencies-

      - run: yarn install
      - run: yarn bootstrap

      - save_cache:
          paths:
            - node_modules
          key: v2a-dependencies-{{ checksum "package.json" }}
      - save_cache:
          paths:
            - demo/node_modules
          key: v2b-dependencies-{{ checksum "demo/package.json" }}
      - save_cache:
          paths:
            - packages/jarl-react/node_modules
          key: v2c-dependencies-{{ checksum "packages/jarl-react/package.json" }}
      - save_cache:
          paths:
            - packages/jarl-react-native/node_modules
          key: v2d-dependencies-{{ checksum "packages/jarl-react-native/package.json" }}
      - save_cache:
          paths:
            - packages/jarl-react-redux/node_modules
          key: v2e-dependencies-{{ checksum "packages/jarl-react-redux/package.json" }}
        
      # run tests!
      - run: yarn lint
      - run: yarn build
      - run: yarn ci-test
      # start up static server in background
      - run:
          command: yarn ci-start
          working_directory: demo
          background: true
      # run E2E
      - run:
          command: yarn ci-cypress
          working_directory: demo
      # kill server
      - run:
          command: yarn ci-stop
          working_directory: demo
