# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: cypress/base:8

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v3a-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v3a-dependencies-
      - restore_cache:
          keys:
            - v3b-dependencies-{{ checksum "demo/package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v3b-dependencies-
      - restore_cache:
          keys:
            - v3c-dependencies-{{ checksum "packages/jarl-react/package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v3c-dependencies-
      - restore_cache:
          keys:
            - v3d-dependencies-{{ checksum "packages/jarl-react-native/package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v3d-dependencies-
      - restore_cache:
          keys:
            - v3e-dependencies-{{ checksum "packages/jarl-react-redux/package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v3e-dependencies-

      - run: yarn

      - save_cache:
          paths:
            - node_modules
          key: v3a-dependencies-{{ checksum "package.json" }}
      - save_cache:
          paths:
            - demo/node_modules
          key: v3b-dependencies-{{ checksum "demo/package.json" }}
      - save_cache:
          paths:
            - packages/jarl-react/node_modules
          key: v3c-dependencies-{{ checksum "packages/jarl-react/package.json" }}
      - save_cache:
          paths:
            - packages/jarl-react-native/node_modules
          key: v3d-dependencies-{{ checksum "packages/jarl-react-native/package.json" }}
      - save_cache:
          paths:
            - packages/jarl-react-redux/node_modules
          key: v3e-dependencies-{{ checksum "packages/jarl-react-redux/package.json" }}

      # run tests!
      - run: yarn lint
      - run: yarn build
      - run: yarn ci-test
      # start up static server in background
      - run:
          command: yarn ci-start
          working_directory: demo
          background: true
      # run E2E
      - run:
          command: yarn ci-cypress
          working_directory: demo
      # kill server
      - run:
          command: yarn ci-stop
          working_directory: demo

      # Deploy this bad boy
      # - setup_remote_docker

  publish:
    docker:
      - image: cypress/base:8
      # Could use a different image but caches will match (?) the cypress image
      # - image: circleci/node:8.11.1
    working_directory: ~/repo
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
            - v3a-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v3a-dependencies-
      - restore_cache:
          keys:
            - v3b-dependencies-{{ checksum "demo/package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v3b-dependencies-
      - restore_cache:
          keys:
            - v3c-dependencies-{{ checksum "packages/jarl-react/package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v3c-dependencies-
      - restore_cache:
          keys:
            - v3d-dependencies-{{ checksum "packages/jarl-react-native/package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v3d-dependencies-
      - restore_cache:
          keys:
            - v3e-dependencies-{{ checksum "packages/jarl-react-redux/package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v3e-dependencies-

      - run: yarn
      - run: yarn build
      # Create auth file for npm
      - run: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
      # For whatever reason lerna publish wasn't finding the auth file,
      # just run them all maniually thru npm
      - run: cd packages/jarl-react && npm publish
      - run: cd packages/jarl-react-native && npm publish
      - run: cd packages/jarl-react-redux && npm publish

workflows:
  version: 2
  tagged-build:
    jobs:
      - build
      # Publish successful builds only on master with version tag
      - publish:
          requires:
            - build
          filters:
            branches:
              only: master
            tags:
              only: /^v[0-9]+(\.[0-9]+)*/
